# Generated by Django 4.2.15 on 2024-08-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontview', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
