# Generated by Django 4.2.15 on 2024-08-19 10:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontview', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField(default=0)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('imagen', models.ImageField(upload_to='uploads/productos/')),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontview.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio', models.FloatField()),
                ('direccion', models.CharField(blank=True, default='', max_length=100)),
                ('tefelono', models.CharField(blank=True, default='', max_length=15)),
                ('fecha', models.DateField(default=datetime.datetime.today)),
                ('estado_pedido', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontview.productos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontview.usuario')),
            ],
        ),
    ]
