# Generated by Django 4.2.15 on 2024-08-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontview', '0005_alter_usuario_email_alter_usuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tefelono',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
