# Generated by Django 4.2.15 on 2024-08-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontview', '0006_usuario_direccion_usuario_tefelono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tefelono',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tefelono',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
    ]
