# Generated by Django 4.2.15 on 2024-09-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontview', '0009_tallas_productos_tallas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='talla',
            field=models.CharField(default='M', max_length=20),
            preserve_default=False,
        ),
    ]
