# Generated by Django 4.2.15 on 2024-09-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontview', '0010_pedido_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='talla',
            field=models.CharField(default='M', max_length=20),
        ),
    ]
